#ifndef __PIN_MAPPING_HPP__
#define __PIN_MAPPING_HPP__

#define PIN_ENCODER_GRANULAR_1 2
#define PIN_ENCODER_GRANULAR_2 3
#define PIN_BUTTON_GRANULAR 1

#define PIN_ENCODER_DELAY_1 4
#define PIN_ENCODER_DELAY_2 5
#define PIN_BUTTON_DELAY 9

#define MCP23017_ADDR_1 7

#endif // __PIN_MAPPING_HPP__
